# Generated by Django 4.2.2 on 2023-07-05 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_alter_team_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='desc',
            new_name='desct',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='img',
            new_name='imgt',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='namet',
        ),
    ]
